# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青自动阅读-2号

on:
  workflow_dispatch:
  schedule:
     - cron: '15 8-22/3 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ_1: ${{ secrets.YOUTH_READ_1 }}
      YOUTH_READ_2: ${{ secrets.YOUTH_READ_2 }}
      YOUTH_READ_3: ${{ secrets.YOUTH_READ_3 }}
      YOUTH_READ_4: ${{ secrets.YOUTH_READ_4 }}
      YOUTH_READ_5: ${{ secrets.YOUTH_READ_5 }}
      YOUTH_READ_6: ${{ secrets.YOUTH_READ_6 }}
      YOUTH_READ_7: ${{ secrets.YOUTH_READ_7 }}
      YOUTH_READ_8: ${{ secrets.YOUTH_READ_8 }}
      YOUTH_READ_9: ${{ secrets.YOUTH_READ_9 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读一】'
        if: env.YOUTH_READ_1
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_1 }}
      - name: '运行 【中青看点自动阅读二】'
        if: env.YOUTH_READ_2
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_2 }}
      - name: '运行 【中青看点自动阅读三】'
        if: env.YOUTH_READ_3
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_3 }}
      - name: '运行 【中青看点自动阅读四】'
        if: env.YOUTH_READ_4
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_4 }}
      - name: '运行 【中青看点自动阅读五】'
        if: env.YOUTH_READ_5
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_5 }}
      - name: '运行 【中青看点自动阅读六】'
        if: env.YOUTH_READ_6
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_6 }}
      - name: '运行 【中青看点自动阅读七】'
        if: env.YOUTH_READ_7
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_7 }}
      - name: '运行 【中青看点自动阅读八】'
        if: env.YOUTH_READ_8
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_8 }}
      - name: '运行 【中青看点自动阅读九】'
        if: env.YOUTH_READ_9
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_9 }}
