# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青自动阅读-3号

on:
  workflow_dispatch:
  schedule:
     - cron: '15 8-22/2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTHREAD_1: ${{ secrets.YOUTHREAD_1 }}
      YOUTHREAD_2: ${{ secrets.YOUTHREAD_2 }}
      YOUTHREAD_3: ${{ secrets.YOUTHREAD_3 }}
      YOUTHREAD_4: ${{ secrets.YOUTHREAD_4 }}
      YOUTHREAD_5: ${{ secrets.YOUTHREAD_5 }}
      YOUTHREAD_6: ${{ secrets.YOUTHREAD_6 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读一【3】】'
        if: env.YOUTHREAD_1
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTHREAD_1 }}
      - name: '运行 【中青看点自动阅读二【3】】'
        if: env.YOUTHREAD_2
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTHREAD_2 }}
      - name: '运行 【中青看点自动阅读三【4】】'
        if: env.YOUTHREAD_3
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTHREAD_3 }}
      - name: '运行 【中青看点自动阅读四【4】】'
        if: env.YOUTHREAD_4
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTHREAD_4 }}
      - name: '运行 【中青看点自动阅读五【5】】'
        if: env.YOUTHREAD_5
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTHREAD_5 }}
      - name: '运行 【中青看点自动阅读六【5】】'
        if: env.YOUTHREAD_6
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTHREAD_6 }}


